[Settings]
ID = 'adamkiss-com'

[build]
command = 'npm run prod'
publish = '__build__'

[build.environment]
NODE_VERSION = '14'

# Redirect default Netlify subdomain to primary domain
[[redirects]]
from="https://adamkiss-com.netlify.app/"
to="https://adamkiss.com/"
status=301

[[redirects]]
from="https://adamkiss-com.netlify.app/*"
to="https://adamkiss.com/:splat"
status=301
